project:
  type: website
  output-dir: project

website:
  title: "Boyi Chen"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: work.qmd
        text: Work

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
